// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkDfJCgnF4SHHWyDKNoyEw7WwGCkM7FYQ',
    appId: '1:305682319496:web:2f9a6e73f3a2722466f73d',
    messagingSenderId: '305682319496',
    projectId: 'lontara-app-d3adc',
    authDomain: 'lontara-app-d3adc.firebaseapp.com',
    storageBucket: 'lontara-app-d3adc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXSdroAc1gS5hsMkiQSKvE19Qd2eC-qQ',
    appId: '1:305682319496:android:c3ae1c9500cdcfad66f73d',
    messagingSenderId: '305682319496',
    projectId: 'lontara-app-d3adc',
    storageBucket: 'lontara-app-d3adc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5S7qaA-XSkJhughLgTHtg8Stx_U8nh5E',
    appId: '1:305682319496:ios:1bbbd4f57bb8bb0b66f73d',
    messagingSenderId: '305682319496',
    projectId: 'lontara-app-d3adc',
    storageBucket: 'lontara-app-d3adc.firebasestorage.app',
    iosBundleId: 'com.example.lontarataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5S7qaA-XSkJhughLgTHtg8Stx_U8nh5E',
    appId: '1:305682319496:ios:1bbbd4f57bb8bb0b66f73d',
    messagingSenderId: '305682319496',
    projectId: 'lontara-app-d3adc',
    storageBucket: 'lontara-app-d3adc.firebasestorage.app',
    iosBundleId: 'com.example.lontarataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkDfJCgnF4SHHWyDKNoyEw7WwGCkM7FYQ',
    appId: '1:305682319496:web:566706a873c1c85e66f73d',
    messagingSenderId: '305682319496',
    projectId: 'lontara-app-d3adc',
    authDomain: 'lontara-app-d3adc.firebaseapp.com',
    storageBucket: 'lontara-app-d3adc.firebasestorage.app',
  );
}
